export const PRODUCTCATALOGUE_FETCH_REQUEST = 'PRODUCTCATALOGUE_FETCH_REQUEST'
export const PRODUCTCATALOGUE_FETCH_SUCCESS = 'PRODUCTCATALOGUE_FETCH_SUCCESS'
export const PRODUCTCATALOGUE_FETCH_FAIL = 'PRODUCTCATALOGUE_FETCH_FAIL'
export const PRODUCTCATALOGUE_FETCH_RESET = 'PRODUCTCATALOGUE_FETCH_RESET'

export const PRODUCTCATALOGUE_ADD_REQUEST = 'PRODUCTCATALOGUE_ADD_REQUEST'
export const PRODUCTCATALOGUE_ADD_SUCCESS = 'PRODUCTCATALOGUE_ADD_SUCCESS'
export const PRODUCTCATALOGUE_ADD_FAIL = 'PRODUCTCATALOGUE_ADD_FAIL'
export const PRODUCTCATALOGUE_ADD_RESET = 'PRODUCTCATALOGUE_ADD_RESET'

export const PRODUCT_FETCH_REQUEST = 'PRODUCT_FETCH_REQUEST'
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS'
export const PRODUCT_FETCH_FAIL = 'PRODUCT_FETCH_FAIL'
export const PRODUCT_FETCH_RESET = 'PRODUCT_FETCH_RESET'

export const PRODUCT_ADD_REQUEST = 'PRODUCT_ADD_REQUEST'
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS'
export const PRODUCT_ADD_FAIL = 'PRODUCT_ADD_FAIL'
export const PRODUCT_ADD_RESET = 'PRODUCT_ADD_RESET'
