// COMPLAINT-LIST CONSTANTS
export const COMPLAINT_FETCH_REQUEST = 'COMPLAINT_FETCH_REQUEST'
export const COMPLAINT_FETCH_SUCCESS = 'COMPLAINT_FETCH_SUCCESS'
export const COMPLAINT_FETCH_FAIL = 'COMPLAINT_FETCH_FAIL'
export const COMPLAINT_FETCH_RESET = 'COMPLAINT_FETCH_RESET'
//FEEDBACK-LIST CONSTANTS
export const FEEDBACK_FETCH_REQUEST = 'FEEDBACK_FETCH_REQUEST'
export const FEEDBACK_FETCH_SUCCESS = 'FEEDBACK_FETCH_SUCCESS'
export const FEEDBACK_FETCH_FAIL = 'FEEDBACK_FETCH_FAIL'
export const FEEDBACK_FETCH_RESET = 'FEEDBACK_FETCH_RESET'
//BUYER-LIST CONSTANTS
export const BUYER_FETCH_REQUEST = 'BUYER_FETCH_REQUEST'
export const BUYER_FETCH_SUCCESS = 'BUYER_FETCH_SUCCESS'
export const BUYER_FETCH_FAIL = 'BUYER_FETCH_FAIL'
export const BUYER_FETCH_RESET = 'BUYER_FETCH_RESET'
//BUYER-LIST CONSTANTS
export const SELLER_FETCH_REQUEST = 'SELLER_FETCH_REQUEST'
export const SELLER_FETCH_SUCCESS = 'SELLER_FETCH_SUCCESS'
export const SELLER_FETCH_FAIL = 'SELLER_FETCH_FAIL'
export const SELLER_FETCH_RESET = 'SELLER_FETCH_RESET'
//PRODUCT-REPORT LIST CONSTANTS
export const PRODREP_FETCH_REQUEST = 'PRODREP_FETCH_REQUEST'
export const PRODREP_FETCH_SUCCESS = 'PRODREP_FETCH_SUCCESS'
export const PRODREP_FETCH_FAIL = 'PRODREP_FETCH_FAIL'
export const PRODREP_FETCH_RESET = 'PRODREP_FETCH_RESET'
//PRODUCT-LIST CONSTANTS
export const PRODLIST_FETCH_REQUEST = 'PRODLIST_FETCH_REQUEST'
export const PRODLIST_FETCH_SUCCESS = 'PRODLIST_FETCH_SUCCESS'
export const PRODLIST_FETCH_FAIL = 'PRODLIST_FETCH_FAIL'
export const PRODLIST_FETCH_RESET = 'PRODLIST_FETCH_RESET'