// COMPLAINT-LIST CONSTANTS
export const COMPLAINT_FETCH_REQUEST = 'COMPLAINT_FETCH_REQUEST'
export const COMPLAINT_FETCH_SUCCESS = 'COMPLAINT_FETCH_SUCCESS'
export const COMPLAINT_FETCH_FAIL = 'COMPLAINT_FETCH_FAIL'
export const COMPLAINT_FETCH_RESET = 'COMPLAINT_FETCH_RESET'

