export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'
export const USER_SIGNOUT = 'USER_SIGNOUT'

export const SELLER_SIGNIN_REQUEST = 'SELLER_SIGNIN_REQUEST'
export const SELLER_SIGNIN_SUCCESS = 'SELLER_SIGNIN_SUCCESS'
export const SELLER_SIGNIN_FAIL = 'SELLER_SIGNIN_FAIL'
export const SELLER_SIGNOUT = 'SELLER_SIGNOUT'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'

export const USER_CART_FETCHING_REQUEST = 'USER_CART_FETCHING_REQUEST'
export const USER_CART_FETCHING_SUCCESS = 'USER_CART_FETCHING_SUCCESS'
export const USER_CART_FETCHING_FAIL = 'USER_CART_FETCHING_FAIL'
